# Generated by Django 4.0.4 on 2022-04-30 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletanea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='capa',
            field=models.FileField(upload_to='capas/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('CM', 'Comédia'), ('CMT', 'Comédia de Terror'), ('CMA', 'Comédia de Ação'), ('CMD', 'Comédia Dramádica'), ('CMR', 'Comédia Romântica'), ('DA', 'Dança'), ('DOC', 'Documentário'), ('DOCF', 'Docuficção'), ('DR', 'Drama'), ('FA', 'Fantasia'), ('FAC', 'Fantasia Científica'), ('FC', 'Ficção Científica'), ('FG', 'Filmes de Guerra'), ('MI', 'Mistério'), ('MU', 'Musical'), ('FP', 'Filme Policial'), ('RO', 'Romance'), ('TE', 'Terror'), ('TH', 'Thriller')], default='AC', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('F', 'Filme'), ('S', 'Série')], default='F', max_length=1),
        ),
    ]
