# Generated by Django 4.0.4 on 2022-05-01 00:15

import ast
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coletanea', '0003_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=ast.Delete, to=settings.AUTH_USER_MODEL),
        ),
    ]
