# Generated by Django 4.0.4 on 2022-05-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletanea', '0004_capa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.DeleteModel(
            name='Capa',
        ),
    ]
