# Generated by Django 4.0.4 on 2022-05-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletanea', '0006_alter_item_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
