# Generated by Django 4.0.4 on 2022-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletanea', '0007_alter_item_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('CM', 'Comédia'), ('CMT', 'Comédia de Terror'), ('CMA', 'Comédia de Ação'), ('CMD', 'Comédia Dramádica'), ('CMR', 'Comédia Romântica'), ('DA', 'Dança'), ('DOC', 'Documentário'), ('DOCF', 'Docuficção'), ('DR', 'Drama'), ('FA', 'Fantasia'), ('FAC', 'Fantasia Científica'), ('FC', 'Ficção Científica'), ('FG', 'Filmes de Guerra'), ('MI', 'Mistério'), ('MU', 'Musical'), ('FP', 'Filme Policial'), ('RO', 'Romance'), ('TE', 'Terror'), ('TH', 'Thriller'), ('', 'none')], default='AC', max_length=4),
        ),
    ]
