# Generated by Django 4.0.4 on 2022-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletanea', '0009_alter_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('CM', 'Comédia')], default='AC', max_length=4),
        ),
    ]
