# Generated by Django 4.0.4 on 2022-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.FileField(upload_to='capas')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('resenha', models.TextField()),
                ('tipo', models.CharField(choices=[('F', 'Filme'), ('S', 'Série')], default='F', max_length=2)),
                ('categoria', models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('CA', 'Cinema de Arte'), ('CM', 'Comédia'), ('CMT', 'Comédia de Terror'), ('CMA', 'Comédia de Ação'), ('CMD', 'Comédia Tramádica'), ('CMR', 'Comédia Romântica'), ('DA', 'Dança'), ('DOC', 'Documentário'), ('DOCF', 'Docuficção'), ('DR', 'Drama'), ('ES', 'Espionagem'), ('FA', 'Faroeste'), ('FA', 'Fantasia'), ('FAC', 'Fantasia Científica'), ('FC', 'Ficção Científica'), ('FT', 'Filmes com Truques'), ('FG', 'Filmes de Guerra'), ('MI', 'Mistério'), ('MU', 'Musical'), ('FP', 'Filme Policial'), ('RO', 'Romance'), ('TE', 'Terror'), ('TH', 'Thriller')], default='AC', max_length=4)),
                ('ano', models.DateField()),
                ('temporadas', models.IntegerField()),
                ('duracao', models.DurationField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
