# Generated by Django 4.0.4 on 2022-04-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_item_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capa',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
